### ISSUE TITLE
Third party plugins

### ISSUE THREAD

**Issue by MicheleLonghi** [vgorloff/AUHost#24]
Hi
not an issue actually. I'm trying to figure out how and if it is possible to use third party plugins with your code, since when AUAudioUnit is intantiated, for 3rd party plugins I have the following error:
`Error Domain=NSOSStatusErrorDomain Code=-3000 "invalidComponentID`
Any hint?

**Comment by vgorloff** [comment]
Hi,

The error code points to the issue with AudioUnit component registration. The `auval` tool can be used for the component registration troubleshooting.

```sh

# To list all components
auval -a

# To verify component
auval -v aufx bpas appl
```

**Comment by MicheleLonghi** [comment]
Thanks for the reply. The problem appears to be the sandbox. No AU2 plugins loaded whit it on. Too bad.

**Comment by vgorloff** [comment]
There is a new Signed and Notarized app release available. It comes with [Hardened Runtime](https://developer.apple.com/documentation/security/hardened_runtime) which allows arbitrary [plug-ins load](https://github.com/vgorloff/AUHost/blob/master/App.entitlements#L11).

If this won't help, then seems only one way possible – ask appropriate Plug-In developer to update Plug-In, sign and notarize it. Here is an example of Signed and Notarized VST3 Plug-In which can be used as a reference - https://github.com/vgorloff/VST3NetSend.
