### ISSUE TITLE
Issues in Sierra

### ISSUE THREAD

**Issue by mattdrepo** [vgorloff/AUHost#29]
Hi there,

not sure if this is a system requirement or not, but version 1.1.13 works in sierra and later builds do not.  Could you fix this if possible to work on 10.12?

**Comment by vgorloff** [comment]
I think 10.14 was set by mistake. In development branch it is fixed. Will make a release next week.

**Comment by mattdrepo** [comment]
Thanks, drop me a message here to let me know when you have - and thanks for the great little app!

**Comment by vgorloff** [comment]
Issue should be resolved in https://github.com/vgorloff/AUHost/releases/tag/1.2.6

**Comment by mattdrepo** [comment]
Just a quick courtesy reply to confirm the app is now working on 10.12.6. Thanks!
